### ISSUE TITLE
truvari collapse- inversions and duplications

### ISSUE THREAD

**Issue by Madelinehazel** [ACEnglish/truvari#108]
Hello, 

Thanks for this tool! I am using truvari to collapse SVs and I'm using `--pctovl` 0.5 to specify a 50% reciprocal overlap between deletions. Is there a reason that this isn't applied to inversions and duplications? From what I can tell, inversion and duplication matching is only restricted by the `--refdist ` and `--pctsize` (as with insertions).

Thanks,
Madeline

**Comment by ACEnglish** [comment]
Hello,

Truvari was initially built for use with sequence-resolved breakpoint-exact DEL and INS, which meant the INS had no span over the reference. Only recently (f0a608877dbbf4c4dee13dbfad3fc52e3afb4b20) in v3.1 did we add a boundary inflation for INS. But I did accidentally leave [the line](https://github.com/ACEnglish/truvari/blob/0e43cb8c878baeb89f23576f3c86a95420364afb/truvari/bench.py#L213) which restricts matching to DEL. 

I'll fix this and have it slated for the next release.

**Comment by ACEnglish** [comment]
Please install from develop if you'd like to use the new fix ([see wiki for details](https://github.com/ACEnglish/truvari/wiki/Installation)]. I've been planning to cut a [v3.2.0](https://github.com/ACEnglish/truvari/wiki/Updates#truvari-32) release on Apr 1st, so your changes will be available to install via `pip` at the end of the week.

**Comment by ACEnglish** [comment]
The change is that `--recovl` is applied to all SV pairs during Matching. So yes, it will be applied to INV and DUPs as well. However, it will also be applied to INS. With the INS boundary changes mentioned above, it seems more faithful to the parameter description and general user expectations for the parameter to be applied to all SV pairs. 

I will note that in [our paper](https://www.biorxiv.org/content/10.1101/2022.02.21.481353v1.full) we found that reciprocal overlap isn't a very robust matching criteria for sequence-resolved, breakpoint exact SVs, which is why the default remains at `0`.

> Interestingly, 402 SV pairs have ≤5% reciprocal-overlap but ≥70% sequence and size similarity. These pairs may indicate alignment ambiguities across repetitive regions (e.g. left-shift vs. right-shift).

**Comment by Madelinehazel** [comment]
Got it, thank you! Looking forward to the next release. Point taken re: robustness of matching criteria, though- will take this into consideration.
