### ISSUE TITLE
refdist flag not working

### ISSUE THREAD

**Issue by Addicted-to-coding** [ACEnglish/truvari#111]
Version : 3.1.0

Error: refdist flag not working

I am running Truvari using the following command with the refdist set to 0, so that I can find exact matches
truvari bench -b ../../example/base_truth.vcf.gz -c crest_sorted.vcf.gz -f /u/home/m/mdistler/scratch/hs37d5.fa  --refdist 0 -o test0

Inspecting the test0/tp-call.vcf file gives me the following

less tp-call.vcf | grep "chr10" | awk '{print $1" " $2}'
##contig=<ID=chr10,length=133797422> 
##contig=<ID=chr10_GL383545v1_alt,length=179254> 
##contig=<ID=chr10_KI270824v1_alt,length=181496> 
##contig=<ID=chr10_GL383546v1_alt,length=309802> 
##contig=<ID=chr10_KI270825v1_alt,length=188315> 
chr10 4289955
chr10 4708285
chr10 6411459
chr10 7076796
chr10 12560236
chr10 24376609
chr10 31443122
chr10 32257650
chr10 61202449
chr10 70786186
chr10 78255434
chr10 78346359
chr10 85522502
chr10 93633222
chr10 94134371
chr10 99034727
chr10 107950439
chr10 108030095
chr10 111572014

However, these locations are no where to be found in the base_truth.vcf.gz file, for example

(base) [mdistler@login3 test0]$ less ../../../example/base_truth.vcf | grep "4289955"
(base) [mdistler@login3 test0]$

Can you please help?

**Comment by ACEnglish** [comment]
I'm unable to recreate this issue.

I used the repository's [testing files](https://github.com/ACEnglish/truvari/tree/develop/repo_utils/test_files) input1.vcf.gz and input2.vcf.gz 

```bash
$ truvari bench -b input1.vcf.gz -c input2.vcf.gz --refdist 0 -f ../../../repo_utils/test_files/reference.fa -o ticket
$ grep "TP" ticket/summary.txt
    "TP-base": 7,
    "TP-call": 7,
    "TP-call_TP-gt": 2,
    "TP-call_FP-gt": 5,
    "TP-base_TP-gt": 2,
    "TP-base_FP-gt": 5,
# So there's 7 exact matches

$ grep -v "#" ticket/tp-base.vcf | cut -f2 | xargs -I {} grep {} tp-call.vcf. wc -l
       7
# 7 hits
```
And going back to the input1.vcf.gz or input2.vcf.gz shows that the hits in `ticket/tp-*.vcf` are all accounted for.

If you could provide example files I can try with those as well. Otherwise I'll just be guessing what's going on e.g. is ` ../../../example/base_truth.vcf` the same as `../../example/base_truth.vcf.gz`? What do any of the calls in `tp-base.vcf` look familiar to `base_truth.vcf*`? 

Also, it should be noted that `--refdist  0` doesn't force identical matches. Two SV can be at the same reference position but have different e.g. length. So you'd also need to specify `--pctsize 1 --pctsim 1` etc

**Comment by Addicted-to-coding** [comment]
I've attached the relevant files for inspection (github isn't letting me upload the .tbi and the .fa)

1) The files ../../../example/base_truth.vcf are the same, we're just going up a directory while inside test0 (the output dir)
2) Even for inexact matches, where pctsize and pctsim are not provided, 
[crest_sorted.vcf.gz](https://github.com/ACEnglish/truvari/files/8406941/crest_sorted.vcf.gz)
[base_truth.vcf.gz](https://github.com/ACEnglish/truvari/files/8406940/base_truth.vcf.gz) the start positions of SV's detected in tp-call.vcf match with the start positions in base_truth.vcf?

**Comment by ACEnglish** [comment]
Ok, I figured out what's happening here. I jumped right into trying to recreate the error without think about the issue.

So REFDIST is how far away two events can be. Events that are overlapping have 0 REFDIST because they have shared bases. We can't calculate REFDIST based on just a single position because SVs have a span over the reference.. which is why StartDistance and EndDistance are annotated inside of the truvari output VCFs.

If you look at [the code](https://github.com/ACEnglish/truvari/blob/9073f2326b836d2c20b0fadf2ef60815f6803c3e/truvari/bench.py#L191) You'll see that REFDIST is just an inflation of the start/end that's applied before checking if there is any overlapping bases. 

If you want the calls with the same boundaries to match, you'll need to use reciprocal overlap `--pctovl 1`

Running this on your example VCFs reports:
```
    "TP-base": 0,
    "TP-call": 0,
```

**Comment by Addicted-to-coding** [comment]
Great, thanks! Keeping refdist 0 was just a sanity check to see if the
option was working. What we're trying to achieve in our study is to find
the calls where both the start and end position of the deletion detected by
the tool lies within t base pairs of the gold standard. For enforcing this,
apart from setting refdist to t, what other parameter settings should we
enforce?

**Comment by Addicted-to-coding** [comment]
For example, when I run 

truvari bench -b ../../example/base_truth.vcf.gz -c crest_sorted.vcf.gz -f /u/home/m/mdistler/scratch/hs37d5.fa --refdist 100 -o test

I get

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/28642161/161581697-f300afe5-e560-4ea4-91a7-7157872448d6.png">
