### ISSUE TITLE
‘truvari collapse -k maxqual‘ does not work for me

### ISSUE THREAD

**Issue by Jixin-Cao** [ACEnglish/truvari#122]
Hi,
Thanks for your great tool! I planned to use 'truvari collapse' to remove duplicate SVs from one sample.  I wanted to collapse variants with at least 1bp of overlap and keep only the max quality callings. The code to use is as follows:
`truvari collapse -O 0.000001 -r 0 -p 0 -P 0 -k maxqual -i B1085_DEL-smoove.genotyped.carried.vcf.gz -o B1085_DEL-smoove.genotyped.merged.vcf -c B1085_DEL-smoove.collapsed.vcf -f ~/human_g1k_v37.fasta`
However, among all overlapped variants, there were only the first mutations kept in the B1085-smoove.genotyped.merged.vcf,  and they were not always the highest quality ones. 
What do you think?

**Comment by ACEnglish** [comment]
Thank you so much for reporting this. Indeed there was a problem with the ordering. I was returning a bool instead of int for my [functools.cmp_to_key](https://www.geeksforgeeks.org/how-does-the-functools-cmp_to_key-function-works-in-python/) functions. Develop now has a fix if you'd like to test using that. This is a big enough problem that I'll try to cut an official v3.3 release soon

**Comment by Jixin-Cao** [comment]
Thank you for your prompt reply! So no matter how the parameters are set, is the first row kept by default? 
By the way, I noticed overlapped SVs in the same sample were reported occasionally by some SV detection software (for example, Manta). For cohort-level VCF, re-genotyped after merging all individuals may also introduce overlapping SVs in the same sample. 
Have you ever had similar issues and do you have any recommendations for solutions?

**Comment by ACEnglish** [comment]
I believe with v3.2 the first variant was always kept regardless of `--keep`. However, the fix for this also exposed that there was a lack of enforced determinism in the sorting. So the safest assumption is that it was just randomly picking a variant. I also just put in [dbdbe55](https://github.com/ACEnglish/truvari/commit/dbdbe55f10fbfd3c150a7403ec35b624a11dc6a4) which will help `collapse` more consistently choose alleles.

I think it would take a long time to fully answer your question - it is a complex subject, to say the least. But, I can point you to our [preprint](https://www.biorxiv.org/content/10.1101/2022.02.21.481353v1) where one of the things we try to show is that there is more allelic diversity than other SV merging tools report. The point being that I have observed overlapping SVs and believe in being cautious about over-merging.

**Comment by Jixin-Cao** [comment]
Interesting research! Thanks again for the useful tool！
