### ISSUE TITLE
Question about logging in collapse

### ISSUE THREAD

**Issue by Meltpinkg** [ACEnglish/truvari#134]
Hello!

Thanks for developing such a great tool. It helps me a lot in my studies on SV.
I used truvari (v3.1.0) collapse to finish SV merge. And I have some questions about the logging output. When finishing the collapsing, it outputs:
```
Zipped 2275967 variants. Counter({'base': 2275967})
87204 chunks of 2275967 variants. Counter({'base': 2264812, '__filtered': 11155})
Wrote 172241 variants
2103726 variants collapsed into 111970 variants
Finish collapse
```
I found there are 172241 variants in the merge output (truvari_merge.vcf). But I wonder what does the other numbers in the log mean? For example, "filtered **11155**", and the variants collapsed into **111970** variants, what's the difference between these **111970** and **172241** variants?

Thanks a lot.

Best,
Shuqi

**Comment by ACEnglish** [comment]
* __filtered is the number of variants that weren't compared to other variants due to being outside of parameter thresholds (e.g. `--sizemin`)
* `Wrote 172241 variants` is how many variants are in your output vcf.
* `2103726 variants collapsed` is how many variants were merged into calls that were kept. They can be found in the `--collapsed-output`.
* `collapsed into 111970 variants` is how many variants in your output VCF had >= 1 variant merged into them. 

So for this example, 65% of your output variants are the representative variant from some number of merged variants. And 2103726 / 111970 or 18:1 is the ratio of how many variants collapsed into the merged representations.

I don't know if it applies to your dataset, but for variants I'm used to dealing with, 18:1 is pretty high. I suspect you've used looser thresholds (e.g. `--pctsim 0`).  I would just caution you to look out for over merging. See [our paper](https://www.biorxiv.org/content/10.1101/2022.02.21.481353v1) for details on what over merging might look like.

**Comment by Meltpinkg** [comment]
Thanks very much for your clear explanation. I've got that! 
I'll check the merging according to your advice.
