### ISSUE TITLE
SVLEN conversion error

### ISSUE THREAD

**Issue by shaze** [ACEnglish/truvari#151]
Running `truvari collapse` I found this error
```
 File "/opt/exp_soft/python310/bin//truvari", line 8, in <module>
    sys.exit(main())
  File "/opt/exp_soft/python310/lib/python3.10/site-packages/truvari/__main__.py", line 102, in main
    TOOLS[args.cmd](args.options)
  File "/opt/exp_soft/python310/lib/python3.10/site-packages/truvari/collapse.py", line 420, in collapse_main
    for call in itertools.chain.from_iterable(map(collapse_chunk, chunks)):
  File "/opt/exp_soft/python310/lib/python3.10/site-packages/truvari/matching.py", line 313, in chunker
    if not matcher.filter_call(entry, key == 'base'):
  File "/opt/exp_soft/python310/lib/python3.10/site-packages/truvari/matching.py", line 153, in filter_call
    size = truvari.entry_size(entry)
  File "/opt/exp_soft/python310/lib/python3.10/site-packages/truvari/comparisons.py", line 318, in entry_size
    size = abs(entry.info["SVLEN"])
TypeError: bad operand type for abs(): 'str'
```

I changed the code to `size = abs(int(entry.info["SVLEN"]))` (and on line 316) and this seems to work

Thanks for a very useful tool

**Comment by ACEnglish** [comment]
I'll have to think about it, but I'll probably only go as far as trying to implement a more informative error and not the int type casting. VCFs can be a pain to deal with because so many of its format specifications read more like "should do" or "can do", instead of "must do". This allows tools a lot of flexibility in how they produce their VCFs.

Because one of Truvari's design goals is to handle as many VCFs as possible, I've - somewhat counterintuitively - chosen to be more strict with VCF handling. The VCF format specification (see https://samtools.github.io/hts-specs/VCFv4.2.pdf Section 3) doesn't explicitly "require" SVLEN to be an Integer, but in their own example they write the header as Type=Integer, and therefore I interpret it as a requirement.

I fully recognize that the int type casting is a very small hill to die on. But as a slippery-slope argument, opening the door to "Make this change for gridds", could allow more changes that are tailored per-tool. I fear this becoming an undue development burden on Truvari where - in this example - the responsibility should lie with gridds to properly define their output. So to sum this up in an overly cold way, blame gridds for the reheadering nuisance.

Hope you understand,
~/Adam
