### ISSUE TITLE
GT-precision calculation

### ISSUE THREAD

**Issue by huangrongbioinfomation** [ACEnglish/truvari#155]
<img width="357" alt="image" src="https://github.com/ACEnglish/truvari/assets/54733697/f57923a0-0567-4f3b-b574-cb930063eb6e">

After analyzing the above results, how to calculate GT-F1, GT-recall, GT-precision

**Comment by ACEnglish** [comment]
Formulas for the metrics and gt_matrix table structure are described in the [wiki](https://github.com/ACEnglish/truvari/wiki/bench#summaryjson). Your table shows

| compGT  | (1,1) | (0,1) |
|---------|------|-----|
| baseGT |        |          |
| (1,1)         | 4305 | 3178 |
|(0,1)          | 4 | 1667 |

If you define TP as compGT == baseGT - you get `4305 + 1667 = 5972`.
The difficulty for applying the metrics to FN/FP genotypes is they're symmetrical since every baseGT has a compGT to compare to. But you could say FN/FP counts are `3178 + 4 = 3182`.  Plugging these totals in gives `0.652392397` precision and recall.

Because of this symmetrical FN/FP, Truvari reports the summary metric as gt_concordance:
`"TP-comp_TP-gt" / ("TP-comp_TP-gt"+ "TP-comp_FP-gt")` Which is also `0.652392397`

**Comment by huangrongbioinfomation** [comment]
Precision = TP / (TP + FP)
"Can we understand this as GT-precision = 0.652392397?"
Recall = TP / (TP + FN)
How to calculate GT-Fn？
How to calculate GT-recall?

**Comment by ACEnglish** [comment]
Please see previous post. Or just use gt_concrdance.
