### ISSUE TITLE
Refine Silently killed.

### ISSUE THREAD

**Issue by Ritu-Kundu** [ACEnglish/truvari#175]
**Version** : 
Truvari v4.1.0

**Describe the bug** : 
I am trying to run `truvari refine` on an HPC node with 256 GB RAM. On 128GB RAM, I got the error message that it was trying to use more than allocated memory (i.e. 128GB). Therefore, I doubled it. Now, the process is killed without any warning/error. I reckon it is probably trying to use more than 256GB. Is there a way to assess the resources required by the step or run in a fixed maximum memory mode?

The file `phab.output.vcf` is being writtten with the last entry from `chr1`. In `candidate.refine.bed`, regions are going up to `chrX`.

**To Reproduce** : 
Following is the log I am getting:
```
023-11-15 05:09:16,279 [INFO] Truvari v4.1.0
2023-11-15 05:09:16,280 [INFO] Command truvari refine --align wfa --use-original-vcfs --recount --debug -t 4 refine_compatible
2023-11-15 05:09:16,281 [INFO] Params:
{
    "benchdir": "refine_compatible",
    "reference": "/myscratch/ref/GRCh38Decoy.fa",
    "regions": null,
    "use_original_vcfs": true,
    "use_region_coords": false,
    "recount": true,
    "threads": 4,
    "align": "wfa",
    "debug": true
}
2023-11-15 05:09:16,281 [INFO] Setting up regions
2023-11-15 05:09:16,340 [INFO] Evaluating 1002 regions
2023-11-15 05:09:18,099 [INFO] 600 regions to be refined
2023-11-15 05:09:18,126 [INFO] Preparing regions
2023-11-15 05:09:18,157 [INFO] Extracting haplotypes
2023-11-15 05:10:57,590 [INFO] Harmonizing variants
```

**Expected behavior** : 
A warning that the RAM might not be sufficient (if that indeed is the case).

**Example Data** : 
I am afraid I can't share the VCFs being compared here.

**Additional context** :
I am trying to benchmark GIAB's draft SV truthset with our in-house one.

**Comment by ACEnglish** [comment]
Refine was built around an assumption that it operates on sub-regions of the genome. This works well for TR regions since they typically only span a couple hundred base pairs.  From what I'm gathering, you're attempting to run this on whole genome, correct? If that's the case, then the small region assumption is broken. This could cause bcftools consensus to have to make very large haplotypes and pywfa make very large alignments; either of which may be the cause of the memory issues.

In v4.1 I added an output in the `truvari bench` directory named `candidate.refine.bed` which has the sub-regions where base/comparison calls didn't match up. To run on these smaller regions, add these first two parameters:
```bash
truvari refine --use_region_coords --regions refine_compatible/candidate.refine.bed \
    --align wfa --use-original-vcfs --recount --debug -t 4 refine_compatible
```

Let me know if that helps.

Have a good day,
~/Adam

**Comment by Ritu-Kundu** [comment]
Hi Adam,

Thanks. It worked.
