### ISSUE TITLE
Unresolved SVs (e.g. ALT=<DEL>)

### ISSUE THREAD

**Issue by poddarharsh15** [ACEnglish/truvari#177]
[log.txt](https://github.com/ACEnglish/truvari/files/13487258/log.txt)
Hi,
I'm currently facing issues with Truvari -bench while detecting deletions in multiple .vcf files. Could you please provide some ideas or suggestions to resolve this?
Thanks in advance.

**Comment by ACEnglish** [comment]
Unresolved SVs (e.g. `<DEL>`) don't have sequences to compare. Therefore, Truvari won't perform sequence comparison and provides the warning to let users know that it is skipping some variants. To remove the warning and to analyze unresolved SVs, turn off sequence comparion with `--pctseq 0` or alter the VCFs manually to place in sequences when possible [details](https://github.com/ACEnglish/truvari/discussions/163#discussioncomment-6607727)

**Comment by poddarharsh15** [comment]
Hi,
Thank you for your response. While running another bench on a .vcf file, I encountered an error related to the absence of 'chr' in the .bed file and truth/base .vcf file. I attempted to remove 'chr' from my .vcf file, but I'm still facing issues. Could you please provide some ideas to address this?
Thanks in advance.
`truvari bench -b HG002_SVs_Tier1_v0.6.vcf.gz -c no_cand_fix.vcf.gz -o Manta_v0.6 --includebed HG002_SVs_Tier1_v0.6.bed -f /home/tigem/h.poddar/input/reference_genome/GRCh37/GRCh37.p13.genome.fa`
![Screenshot from 2023-11-29 11-05-26](https://github.com/ACEnglish/truvari/assets/45700858/6ffdebbf-6907-46ff-ae84-e06766dce40f)
[no_cand_fix.vcf.gz](https://github.com/ACEnglish/truvari/files/13499037/no_cand_fix.vcf.gz)
[HG002_SVs_Tier1_v0.6.vcf.gz](https://github.com/ACEnglish/truvari/files/13499041/HG002_SVs_Tier1_v0.6.vcf.gz)

**Comment by ACEnglish** [comment]
You failed to remove chr from your vcf. You took 'chr' characters from the entry lines, but the 'no_cand' vcf has the contigs defined in the header (e.g. `##contig=<ID=chr1,length=249250621>`). The error raised by truvari seems to point to this same issue. Please familiarize yourself with [VCF format specifications](https://samtools.github.io/hts-specs/VCFv4.2.pdf).

**Comment by leone93** [comment]
Encountering the same problem. I would like to understand better what you mean here and in the wiki for "Truvari won't perform sequence comparison and provides the warning to let users know that it is skipping some variants."; beacuse when I run truvari (4.1 or 4.2.1-dev) I found this warning "[WARNING] Unresolved SVs (e.g. ALT=<DEL>) are filtered when `--pctseq != 0`".
To me, filtering is different from skipping the sequence control. Are the software removing these variants or just don't control the sequences for these? 
I think an option to automatically skip the sequence control of these particular cases when the software finds these variants and instead do the control when the sequence is there will be useful. So leaving the pctseq different from zero but skipping the control only in this case.

**Comment by ACEnglish** [comment]
I don't think I'm understanding your question/request. So if the below response isn't relevant to what you're saying, please let me know.
Symbolic variants are filtered/skipped when `--pctseq != 0` the same as FILTER==FAIL variants are filtered/skipped when `--passonly` is used.

If you're asking Truvari to dynamically decide what similarity metrics are applicable, that could have unwanted consequences. 

For example, say there's two SV results A & B which `truvari bench (default params)` report as having e.g. 92% f1. But, if result A has sequence resolved SVs and B is all symbolic variants, those f1s are not equal since result A has more information. 

Or, for example, say you're merging two symbolic SVs with `truvari collapse --pctseq 0.70` that are end-to-end. 
```
       |   DEL1  |   DEL2  |
REF CGCAAAAAAAAAATTTTTTTTTTCGC
```
If they aren't sequence resolved and Truvari merges them, it hasn't respected the threshold `--pctseq 0.70` since it has merged two SVs that have 0% sequence similarity.

This second example shows that there are ways to fill in symbolic variants since they're generally just a short-cut for VCFs. For the DEL exampls, we'd simply need to pull the reference sequence so that the VCF record 
```
REF 3 . C <DEL> ...
```
Becomes
```
REF 3 . CAAAAAAAAAA C  ...
```

Also, in case this is what you're asking: For `truvari bench` these variants are put into a 'filter' part of a data structure and not analyzed as part of the performance metrics. For `truvari collapse` these variants are put into the same 'filter' and unanalyzed, but the variants are preserved, unmanipulated, in the output.

**Comment by poddarharsh15** [comment]
Hello @ACEnglish,
I've been running the truvari refine command for the past three weeks, and it hasn't finished yet. Is it normal for this process to take such a long time, or should I consider any adjustments or optimizations?
`truvari refine --regions ~/short_reads_pipelines/pipelines/truvari/manta/candidate.refine.bed --use-original-vcfs --reference /home/tigem/h.poddar/short_reads_pipelines/ref_genome/GRCh38/GRCh38.primary_assembly.genome.fa  ~/short_reads_pipelines/pipelines/truvari/manta/ -t 30`

Thank you.

**Comment by ACEnglish** [comment]
Depending on what you're benchmarking, your parameters need to be different. I assume you're doing whole genome benchmarking, and if so your command is missing a parameters `--use-region-coords`. ([details](https://github.com/ACEnglish/truvari/wiki/refine)).

**Comment by ACEnglish** [comment]
Also, please make sure that the genotypes are phased. The `refine` procedure attempts to create two haplotypes over each region for the baseline and comparison VCFs and aligns them with the `--align` procedure. If the regions are too large the realignment isn't computationally feasible. If the variants are not phased, the haplotypes created will not be correct. Work to improve the usability/flexibility of this step is under ongoing research.
