### ISSUE TITLE
GT integrate

### ISSUE THREAD

**Issue by xiaomiyongyuan** [ACEnglish/truvari#199]
Hi:
I want to ask this:
**before:**
chr1    744867  .       g       GTATATATATATATATA       .       .       .       GT      ./.     1/.
chr1    744867  .       g       GTATATATATATATATATA     .       .       .       GT      1/.     ./.

`truvari collapse -s 0 -S 50 -p 0.7 -P 0.7 -i "sort"$file".gz" -o "./truvarimerge/${file}_merge.vcf" -c "./truvarimerge/${file}_collapsed.vcf" -f "/home/jmhan/SDR/genome/GRCh38/GCF_000001405.26_GRCh38_genomic.chrNames.fna"`

${file}_merge.vcf:
chr1    744867  .       g       GTATATATATATATATATA     .       .       NumCollapsed=1;NumConsolidated=0;CollapseId=15.0        GT      1/.     ./.

why this phenotype isn't
chr1    744867  .       g       GTATATATATATATATATA     .       .       NumCollapsed=1;NumConsolidated=0;CollapseId=15.0        GT      1/.     1/.

Thank you !

**Comment by ACEnglish** [comment]
I believe what's happening here is that because they're partial missing genotypes (the `.` in `./1`), the calls are going through a branch of the code that isn't consolidating the genotypes. A short term solution would be to alter the VCF so that it fills in `.` with `0`. A long term solution will be for me to revisit the genotype handling logic.
