### ISSUE TITLE
Validity of unphased tandem repeat VCFs

### ISSUE THREAD

**Issue by davidlougheed** [ACEnglish/truvari#243]
Hello,

I'm in the process of benchmarking some tandem repeat callers using the new GIAB TR benchmark. Most TR callers don't output phased variants by default unless provided with phased reads (which means that some aspects of the caller, i.e. peak calling, go untested). 

I'm curious as to the validity of running benchmarking on unphased TR VCFs with Truvari. It is warned against with refine/phab – obviously, phase errors will be missed, and if two variants are side-by-side, it can create errors. However, if the regions being tested were some distance away from each other, would the Truvari results be somewhat accurate?

**Comment by davidlougheed** [comment]
Also, an aside: when benchmarking with a whole-genome subset (just STRs) with the GIAB TR benchmark, should `--use-region-coords` be used?

**Comment by ACEnglish** [comment]
Hey, 

It is possible to run refine/phab on unphased VCFs, and in many cases it will work out fine. The problem occurs when any TR region has two het SVs. For example:

```
chr1    1000    ATATATATATA    A    0/1
chr1    1005    ATATATATATA    A    0/1
```
Phab won't be able to properly reconstruct haplotypes over the region. Instead, in this example, it'll skip a variant since it can't traverse a path to find the second, overlapping variant. Or, if the hets aren't overlapping, it will incorporate both hets into the same haplotype. For the non-overlapping case, sometimes that's okay (e.g. `0|1 & 0|1`), but if the variants are from opposite haplotypes, combining into a single haplotype will create an incorrect sequence that will MSA into something that will produce a wrong alignment.

`--use-region-coords` is for cases when one wants to harmonize within the regions they're providing to `truvari refine --regions`. Since the TR benchmark is run on the boundaries which need to be harmonized from `truvari bench --includebed`, `--use-region-coords` isn't needed. Instead, if one were running whole-genome benchmarking and there are specific regions that need to be refined, that's when you'd use their coordinates. This prevents attempting to run mafft/poa on extremly long regions. Typically, `--use-region-coords` is for refining a subset of a whole-genome includebed via `truvari refine --use-region-coords --regions bench_result/candidate.refine.bed`

**Comment by davidlougheed** [comment]
@ACEnglish if `--use-region-coords` isn't for this use case, I'm wondering what to do with the TR benchmark when there are regions included outside of the TRF repeat (but inside the TRregions BED) that have indels, which to me shouldn't count as false negatives. For example:

chr4:3300461 is in `HG002_GRCh38_TandemRepeats_v1.0.1.vcf.gz` with a `0|1` genotype, and the motif CCTGGGAGGAGGAGGACTG:

```
chr4    3300461 .       C       CCCTGGGAGGAGGAGGACTG    60      PASS    SVTYPE=INS;SVLEN=19;AN=2;AC=1;NS=86;AF=0.127907;MAF=0.127907;AC_Het=20;AC_Hom=2;AC_Hemi=0;HWE=1;ExcHet=0.595244;TRF;TRFdiff=0;TRFrepeat=CCTGGGAGGAGGAGGACTG;TRFovl=1;TRFstart=3300461;TRFend=3300505;TRFperiod=19;TRFcopies=2.3;TRFscore=132;TRFentropy=1.74    GT:FT:AD        0|1:PASS:1,1
```

However, I only wish to test STRs, i.e., motifs <~10bp±. In `adotto_TRregions_v1.2.bed`, this is covered by an STR with the following line:

```
chr4	3300441	3300501	1	24	25	0	0	1	1	96	100	.	.	.	1	protein_coding	"[{""chrom"": ""chr4"", ""start"": 3300465, ""end"": 3300476, ""period"": 3.0, ""copies"": 4.0, ""score"": 36, ""entropy"": 0.92, ""ovl_flag"": 1, ""motif"": ""GGA"", ""purity"": 96}]"
```

This TRF definition is mismatched, leading to a false negative where I'm not expecting one - since it's outside of the TRF coordinates from the TRregions BED TRF definition (which becomes the list of regions for STR callers to process), but inside the coordinates of the BED file itself.

**Comment by ACEnglish** [comment]
That's more complicated. 

First, alignment ambiguities can cause TRs to 'slip' out of the boundaries of a TR annotation. That is to say, there is enforcement of an expansion/contraction INDEL to occur within the region. Therefore, the adotto regions have buffers to help ensure that any plausable variant placement which would correspond to a TR is captured.

Second, motif annotations on TRs are, by definition, dependent on the sequences. This example is a case where given only the reference sequence, TRF believes the motif is an STR, but when given the HG002 haplotype over the region, TRF believes the motif should be a VNTR. This is part of the reason why the GIABTR benchmark doesn't separate motifs by length.

For your case, you could exclude GIAB TR regions you're not interested in by either:
1.  removing them from the `truvari bench --includebed`
2. providing a `truvari refine --regions` bed which only contains the subset of regions you're interested in. Refine will then only analyze the subset of `--includebed` regions which intersect the `--regions`.
3. Similar to step 2, but with a `--regions` bed you've created with a more restrictive set of boundaries which would exclude specific variants you're not interested in. At which point you'd use `--use-region-coords`.  
 
Note that this option 3 is a little tricker because you not only need to define those more exact boundaries but also account for the buffer sequence which `phab` will use to help anchor the MSA. For example, if a TR region over the positions 75-125 has a 'VNTR' expansion at position 100, and an 'STR' at 110, making a new TR region from 110-125 may still grab the VNTR since phab tries to build the haplotype from start-buffer, end+buffer, and buffer is hardcoded at 100bp.

**Comment by davidlougheed** [comment]
thank you for the comprehensive reply!
