### ISSUE TITLE
Information about calculating AF using truvari-anno

### ISSUE THREAD

**Issue by poddarharsh15** [ACEnglish/truvari#244]
Hi @ACEnglish 

I have 300 samples analyzed with Dysgu as the SV caller. 
For my study, I need to calculate AF using only my cohort. I'm considering using vcfanno (via Truvari) to fill in these fields.
Planned Steps:
1.Merge VCFs:
`bcftools merge -m none -Oz -o "${merged_vcf}" ${output_dir}/*.tagged.vcf.gz`

2.Use Truvari collapse: 
`truvari collapse --refdist 0 -p 0 -P 0 -f "${REFERENCE}" --sizemax 1000000 -i "${filtered_vcf}" -o "${final_output}" -c "${final_collapse}"
`
3.Apply Truvari anno to calculate AF on my cohort.

**Questions**:
1.Will vcfanno handle the AF calculation accurately on 300 samples?
2.Any parameter adjustments recommended for minimizing errors?

Thank you in advance for suggestions!

**Comment by ACEnglish** [comment]
If you're only interested in overall AF, `truvari anno grpaf` is largely a reimplementation of `bcftools +fill-tags` for calculating AF. I would probably stick to bcftools unless you're specifically interested in the extra functionality of annotating AF for subsets of samples easily.

Those parameters will work technically, but I would caution that they will also likely severely overmerge the SVs [details](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-022-02840-6) and end up with inflated AFs. Since ~70% of SVs occur within the highly polymorphic TRs [cite](https://www.nature.com/articles/s41587-024-02225-z), you'll likely end up finding a binary status of present (mainly) and absent over TR loci instead of any refined signature truly representing allelic diversity. Ballpark values of QC metrics on 'well called' SVs is a per-sample variant count around 25-30k SVs and het/hom ratio approaching 4 [cite](https://www.biorxiv.org/content/10.1101/2024.10.22.619642v1). 

Good luck!

**Comment by poddarharsh15** [comment]
Hi @ACEnglish ,

I was wondering if I can use the `SVAFotate` tool to calculate allele frequency, as I'm getting some unexpected results with bcftools. Would SVAFotate be a better option for more accurate AF calculations?

Thanks!

**Comment by ACEnglish** [comment]
I do not maintain svafotate
