### ISSUE TITLE
Understanding the refine.variant_summary.json

### ISSUE THREAD

**Issue by yangao07** [ACEnglish/truvari#250]
Hi Adam,

Thanks again for developing this tool! Great work!

I used truvari bench + refine to benchmark 3 SV callers. Here is what I get from "refine.variant_summary.json."

| Tool     | Type | Filter | TP-base    | TP-comp     | FP   | FN   | base cnt  | comp cnt | precision | pecall  | f1 |
|----------|------|--------|--------|--------|------|------|--------|---------|-----------|---------|----------|
| Sniffles | SV   | PASS   | 20,815 | 18,734 | 616  | 1,742 | 22,557 | 19,350  | 96.817%   | 92.277% | 94.492%  |
| Sawfish  | SV   | PASS   | 22,489 | 21,144 | 720  | 895   | 23,384 | 21,864  | 96.707%   | 96.173% | 96.439%  |
| CuteSV   | SV   | PASS   | 19,770 | 17,068 | 452  | 1,842 | 21,612 | 17,520  | 97.420%   | 91.477% | 94.355%  |

I used the same benchmarking BED region file for 3 tools.
So, why the base counts are different for 3 tools? 
Thank you!

**Comment by ACEnglish** [comment]
Refine creates a multiple sequence alignment (MSA) between all the haplotypes described by the baseline VCF, comparison VCF, and reference spanned by the bed file regions. The optimal MSA for a locus when including e.g. a Sniffles haplotype vs a Sawfish haplotype may need a different set of mismatches / insertions / deletions if their VCF entries are not describing the exact same sequences. Therefore, a different number of variants between runs is expected because harmonization is relative to the input. While this is expected, I agree it's not optimal and we'd prefer a universal variant count between runs so that they're more directly comparable. However, the nature of variants only existing as a result of an alignment procedure means the only way to enforce constant variant counts would be to prevent any and all alignment ambiguity - which (likely) isn't possible for the highly repetitive sequences around SVs - or enforce variant representation standards beyond simple INS/DEL - which would be a fool's errand. Fortunately, the precision/recall metrics normalize by counts and are therefore more comparable between runs. The precision/recall metrics you're showing are in-line with my expectations for each of these tools, so I think your results are probably valid. And I'll let you know that I'm actively working with GIAB to address at least the prevalence of this 'variant count' issue in the draft v1.1.

**Comment by ACEnglish** [comment]
If you're feeling adventurous, I just thought up an experiment that might better harmonize the variant representations and counts for comparison between callers.

If you run `bcftools merge` on the baseline, sniffles, sawfish, and cuteSV VCFs, you should be able to directly run `truvari phab` on the merged VCF to harmonize all 8 haplotypes together with the reference. You can then run `truvari bench -b merged.phab.vcf.gz -c merged.phab.vcf.gz --no-ref a --bSample baseline --cSample sniffles -o bench_result_sniffles` (where bSample and cSample correspond to SAMPLE column names in the merged vcf). 

This phab -> bench is essentially what refine is doing and by running phab on all haplotypes at once, they'll have more consistent representations across with one another and *should* all have the same baseline counts. This is experimental and something I've never done before, so I'm not positive it'll work, but I'm fairly confident it will, and might be an interesting result.

**Comment by yangao07** [comment]
The benchmark set I used was indeed the T2T v1.1.
I am trying your proposed experimental way of running it and will update you when I get the result.
Thanks!
